[
    count1: number;
    result1: number;
    count2: number;
    result2: number;
    count3: number;
    result3: number;
    count4: number;
    result4: number;



#	count = 1;

#	result = 2
#    in => counter;
#
#    until (counter > 0) [
#        result = result  + calculate(counter, result);
#        counter = counter - 1;
#    ]
#
#    out <= result;
#
#    number opr calculate(a: number, b: number): number [
#        result: number = a * b + 2;
#        send result;
#    ]
]